Реализация gophkeeper с tui
k0st1a/gophkeeper pull request #1
Opened 2024-10-20 19:41 UTC by k0st1a

На текущий момент не все сделано, но т.к. времени осталось мало, то, думаю, текущего кода будет достаточно для принятия проекта.

Что сделано:
* серверная сторона по работе к предмета/юзера gophkeeper-а
* локальное хранилище предметов клиента
* синхронизация предметов клиента и сервера
* tui

Что хотелось сделать, но не сделано:
* шифрование серверных предметов 
* паджинация при синхронизации предметов (сейчас вычитывается все за раз)
* паджинацию предметов для tui (сейчас вычитывается все за раз)
* юнит и интеграционные тесты (не успеваю по сроку)
* github ci для запуска тестов
* github ci для сборки релиза

Моменты:
* от swagger решил отказаться, много времени на него потратил
* tui работает - проверял ручками)
* тесты (юнит и интеграционные) напишу в дальнейшем, без них не комильфо)

Как запустить:
* запускаем db командой `make db-up`
* командой `make` собираем клиента и сервера
* командой `make server-run-with-args` запускаем сервер
* командой `make client-run-with-args` запускаем tui клиента. Нужно зарегистрироваться, залогиниться и посоздавать/удалять/обновить предметы.
* P.S. командой `make client-run-with-args-2` можно запустить 2-ого клиента

2024-10-28 20:27 UTC, avhitrov requested changes
Практически отлично!
- Есть одно забытое текстовое поле, которое имеет смысл протащить на уровне модели Item. В остальном придраться особо не к чему.
- Есть предложение подумать о защите проекта.

2024-10-28 20:27 UTC, avhitrov commented on internal/pkg/client/model/item.go
> +	File     *File     `json:"file"`
Позволю себе зацитировать ТЗ:
```
Для любых данных должна быть возможность хранения произвольной текстовой метаинформации (принадлежность данных к веб-сайту, личности или банку, списки одноразовых кодов активации и прочее).
```

2024-10-31 01:03 UTC, k0st1a commented on internal/pkg/client/model/item.go
> +	File     *File     `json:"file"`
Поправил в рамках коммита [9be99a11961984bee009f3d29136b29e73dde5ac](https://github.com/k0st1a/gophkeeper/pull/1/commits/9be99a11961984bee009f3d29136b29e73dde5ac)

2024-10-31 01:04 UTC, k0st1a commented on internal/pkg/client/model/item.go
> +	File     *File     `json:"file"`
Касательно защиты, можно попробовать)

2024-11-07 21:45 UTC, avhitrov approved these changes
Все ок. Поздравляю с завершением дипломной работы!

2024-11-09 06:23 UTC, merged